<a href="https://colab.research.google.com/github/ParnianH98/Adversarial-Search-by-MinMax/blob/main/Obstruction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from math import inf as infinity
import random

global variables

making the board

In [ ]:
hum, comp = 1 , -1
n = 4
global board
board = np.zeros((n,n))
##### in the board:
##### 0 is empty
##### 1 is human
##### -1 is computer
##### 3 is forbidden

evaluate each fill board

In [ ]:
def evaluate():
  global counter
  global first
  if (counter%2 == 1 and first == 'Y'):
    return 10
  if (counter%2 == 1 and first == 'N'):
    return -10
  if (counter%2 == 0 and first == 'Y'):
    return -10
  else:
    return 10

construction of emptyCell

In [ ]:
def emptyCellCons(state):
    emptyCell = []
    a = np.where(state == 0)
    x = a[0]
    y = a[1]
    for i in range(len(x)):
        emptyCell.append([x[i],y[i]])

    return emptyCell

remove neighbours of a specific cell from the board and emptyCell list

In [ ]:
def remNeighbour(state, x,y):
  l = []
  if (x-1 >= 0):
    if (y-1 >= 0):
      state[x-1][y-1] = 3
      l.append([x-1,y-1])
    state[x-1][y] = 3
    l.append([x-1,y])
    if (y+1 < n):
      state[x-1][y+1] = 3
      l.append([x-1,y+1])

  if (y-1 >= 0):
      state[x][y-1] = 3
      l.append([x,y-1])
  if (y+1 < n):
      state[x][y+1] = 3
      l.append([x,y+1])

  if (x+1 < n):
    if (y-1 >= 0):
      state[x+1][y-1] = 3
      l.append([x+1,y-1])
    state[x+1][y] = 3
    l.append([x+1,y])
    if (y+1 < n):
      state[x+1][y+1] = 3
      l.append([x+1,y+1])

  return [state,l]

return neighbours of a specific cell to the board and emptyCell list

In [ ]:
def retNeighbour(state , l):

  for cell in l:
    state[cell[0]][cell[1]] = 0

  return state


is the cell entered by user, available in the list?

In [ ]:
def validMove(x,y,emptyCell):
  if [x,y] in emptyCell:
    return True
  return False

implementation of MiniMax algorithm

In [ ]:
def minimax( state,depth, player) :

    emptyCell = emptyCellCons(state)

    if (player == hum) :
      best = [-1,-1,-infinity]
 
    if (player == comp) :
      best = [-1,-1,infinity]
 
    if depth == 0:
        return [-1, -1, (-1)*player*10]
 
    empty = emptyCell.copy()
    # Traverse all cells
    # Check if cell is empty
    for cell in emptyCell :
        # Make the move
        x = cell[0]
        y = cell[1]
        state[x][y] = player
 
 
        # Call minimax recursively and choose
        # the maximum value
        reserve = remNeighbour(state,x,y)
        state = reserve[0]
        l = reserve[1]
        empty = emptyCellCons(state)
        
        value = minimax( state,len(empty), (-1)*player)
        value[0],value[1] = x,y

        state[x][y] = 0
        state = retNeighbour(state , l)
        empty = emptyCellCons(state)
 
        if player == comp:
            if value[2] < best[2]:
                best = value  # min value
        else:
            if value[2] > best[2]:
                best = value  # max value
        # Undo the move
        
    return best

In [ ]:
def comp_turn():
    global counter
    global board
    emptyCell = emptyCellCons(board)
    depth = len(emptyCell)
    if depth == 0:
        return
 
    print('Computer turn')
 
    if depth == n**2:
        x = random.randint(0,n-1)
        y = random.randint(0,n-1)
    else:
        print(emptyCell)
        move = minimax(board,depth, comp)
        print(emptyCell)
        x, y = move[0], move[1]
        print(emptyCell)
 
    print(emptyCell)
    board[x][y] = -1
    board = remNeighbour(board,x,y)[0]
    emptyCell = emptyCellCons(board)
    print(emptyCell)
 
    counter +=1
    print(board)
    return emptyCell

In [ ]:
def hum_turn():
    global counter
    global board
    emptyCell = emptyCellCons(board)
    depth = len(emptyCell)
    if depth == 0:
        return
 
    while (depth > 0):
      print("your turn!")
      print("input the coordinates x,y:")
      x = int(input("x:"))
      y = int(input("y:"))
 
      if (validMove(x,y,emptyCell)):
        board[x][y] = 1
        board = remNeighbour(board,x,y)[0]
        emptyCell = emptyCellCons(board)
 
        counter+=1
        print(board)
        return emptyCell
 
      else:
        print("input a valid cell!")

In [ ]:
def main():
  
    global counter
    counter = 0

    emptyCell = emptyCellCons(board)
    print(emptyCell)
    global first  # if human is the first
    first = ''

    while first != 'Y' and first != 'N':
        try:
            first = input('First to start?[y/n]: ').upper()
        except (KeyError, ValueError):
            print('Bad choice')
 
 
    # Main loop of this game
    while len(emptyCell) > 0:
        if first == 'N':
            
            emptyCell = comp_turn()
            first = ''
        emptyCell = hum_turn()
        print(emptyCell)
        
        emptyCell = comp_turn()
        print(emptyCell)
 
    if evaluate()>0:
      print("You won!")
    else:
      print("You lost!")

In [ ]:
main()

[[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2], [3, 3]]
First to start?[y/n]: n
Computer turn
[[0, 0], [0, 1], [0, 2], [0, 3], [1, 0], [1, 1], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2], [3, 3]]
[[0, 2], [0, 3], [1, 2], [1, 3], [2, 0], [2, 1], [2, 2], [2, 3], [3, 0], [3, 1], [3, 2], [3, 3]]
[[-1.  3.  0.  0.]
 [ 3.  3.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
your turn!
input the coordinates x,y:
x:2
y:2
[[-1.  3.  0.  0.]
 [ 3.  3.  3.  3.]
 [ 0.  3.  1.  3.]
 [ 0.  3.  3.  3.]]
[[0, 2], [0, 3], [2, 0], [3, 0]]
Computer turn
[[0, 2], [0, 3], [2, 0], [3, 0]]


RecursionError: ignored