<a href="https://colab.research.google.com/github/ParnianH98/Adversarial-Search-by-MinMax/blob/main/Tic_Tac_Toe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from math import inf as infinity
import random

global variables

In [ ]:
hum, comp = 1 , -1
n = 3
global board
board = np.zeros((n,n))

construct emptyCell of a state

In [ ]:
def emptyCellCons(state):
    emptyCell = []
    a = np.where(state == 0)
    x = a[0]
    y = a[1]
    for i in range(len(x)):
        emptyCell.append([x[i],y[i]])

    return emptyCell

is the entered cell valid to be placed?

In [ ]:
def validMove(x,y,emptyCell):
  if [x,y] in emptyCell:
    return True
  return False

what is the state of the game? does anybody win? is it a draw or i have to continue?

In [ ]:
def evaluate(state):
  # Rows
    for row in range(n) : 
      i = 0
      while (i<n-1 and state[row][i] == state[row][i+1]):   
        i+=1
      if i == n-1 :
        if (state[row][0] == hum) :
          return 10
        elif (state[row][0] == comp) :
          return -10
 
  # Columns
    for col in range(n) : 
      i = 0
      while (i<n-1 and state[i][col] == state[i+1][col]):   
        i+=1
      if i == n-1 :
        if (state[0][col] == hum) :
          return 10
        elif (state[0][col] == comp) :
          return -10
 
 
    # Diagonals
    i = 0
    j = 0
    while (i<n-1 and state[i][j] == state[i+1][j+1]):   
      i+=1
      j+=1
    if i == n-1 :
      if (state[0][0] == hum) :
        return 10
      elif (state[0][0] == comp) :
        return -10
 
    i = 0
    j = n-1
    while (i<n-1 and state[i][j] == state[i+1][j-1]):   
      i+=1
      j-=1
    if i == n-1 :
      if (state[0][n-1] == hum) :
        return 10
      elif (state[0][n-1] == comp) :
        return -10
 
    # No victory recognized
    return 0
 

recursively traverce the whole game tree and find the best cell to select for a given player based on the evaluate function

In [ ]:
def minimax(state, depth, player):
    emptyCell = emptyCellCons(state)

    if player == hum:
        best = [-1, -1, -infinity]
    else:
        best = [-1, -1, infinity]

    value = evaluate(state)
    if depth == 0 or value<0:
        return [-1, -1, value]

    for cell in emptyCell:
        x, y = cell[0], cell[1]
        state[x][y] = player
        value = minimax(state, depth - 1, (-1)*player)
        state[x][y] = 0
        value[0], value[1] = x, y

        if player == hum:
            if value[2] > best[2]:
                best = value  # max value
        else:
            if value[2] < best[2]:
                best = value  # min value

    return best

if it is computer turn, what should it do?

In [ ]:
def comp_turn(emptyCell):
    print("comp")
    global board
    
    depth = emptyCell and len(emptyCell)
    value = evaluate(board)
    if depth == 0:
        return
 
    print('Computer turn')
 
    if depth == n**2:
        x = random.randint(0,n-1)
        y = random.randint(0,n-1)
    else:
        move = minimax(board,depth, comp)
        x, y = move[0], move[1]
 
    board[x][y] = -1
    emptyCell.remove([x,y])
    print(emptyCell)
 
    print(board)
    return emptyCell

what to do if its the users turn?

In [ ]:
def hum_turn(emptyCell):
    global board
    depth = emptyCell and len(emptyCell)
    value = evaluate(board)
    if depth == 0:
        return
 
    while (depth > 0):
      print("your turn!")
      print("input the coordinates x,y:")
      x = int(input("x:"))
      y = int(input("y:"))
 
      if (validMove(x,y,emptyCell)):
        board[x][y] = 1
        emptyCell.remove([x,y])
 
        print(board)
        return emptyCell
 
      else:
        print("input a valid cell!")

In [ ]:
def main():
  
    emptyCell = emptyCellCons(board)
    print(emptyCell)
    global first  # if human is the first
    first = ''

    while first != 'Y' and first != 'N':
        try:
            first = input('First to start?[y/n]: ').upper()
        except (KeyError, ValueError):
            print('Bad choice')
 
 
    # Main loop of this game
    while (emptyCell and len(emptyCell) > 0):
        if first == 'N':
            
            emptyCell = comp_turn(emptyCell)
            first = ''
        emptyCell = hum_turn(emptyCell)
        print(emptyCell)
        eval = evaluate(board)
        if eval != 0:
          break
        
        emptyCell = comp_turn(emptyCell)
        print(emptyCell)
        eval = evaluate(board)
        if eval != 0:
          break
 
    
    if eval>0:
      print("You won!")
    elif eval>0:
      print("You lost!")
    else:
      print("Draw!")

In [ ]:
main()


[[0, 0], [0, 1], [0, 2], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]
First to start?[y/n]: n
comp
Computer turn
[[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]
[[ 0.  0. -1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
hum
[[0, 0], [0, 1], [1, 0], [1, 1], [1, 2], [2, 0], [2, 1], [2, 2]]
8
0
your turn!
input the coordinates x,y:
x:1
y:1
[[ 0.  0. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[0, 0], [0, 1], [1, 0], [1, 2], [2, 0], [2, 1], [2, 2]]
comp
Computer turn
[[0, 1], [1, 0], [1, 2], [2, 0], [2, 1], [2, 2]]
[[-1.  0. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[0, 1], [1, 0], [1, 2], [2, 0], [2, 1], [2, 2]]
hum
[[0, 1], [1, 0], [1, 2], [2, 0], [2, 1], [2, 2]]
6
0
your turn!
input the coordinates x,y:
x:0
y:1
[[-1.  1. -1.]
 [ 0.  1.  0.]
 [ 0.  0.  0.]]
[[1, 0], [1, 2], [2, 0], [2, 1], [2, 2]]
comp
Computer turn
[[1, 2], [2, 0], [2, 1], [2, 2]]
[[-1.  1. -1.]
 [-1.  1.  0.]
 [ 0.  0.  0.]]
[[1, 2], [2, 0], [2, 1], [2, 2]]
hum
[[1, 2], [2, 0], [2, 1], [2, 2]]
4
0
your turn!
input the coord